# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    update_project_team(path: "CI.xcodeproj", teamid: "E5P9GHJFJ8")
    match

    gym(
      scheme: "CI",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "fr.OwlGames.CI" => "54bc1074-aece-4408-b9fb-cf51109207bf"
        }
      }
    )
    #    upload_to_testflight
  end
end
